config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :comments, :posts, :blogs
  get 'post/:id/comment_new' => 'comments#comment_new'
  get 'post/:id/comment_new_first' => 'comments#comment_new_first'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :description, presence: true
  has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :title, presence: true
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :description, presence: true
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[edit update destroy show]

  def index
    @blogs = Blog.all
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to action: 'index', notice: 'post was successfully destroyed.' }
      format.js { render layout: false }
    end
  end

  def edit; end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to action: 'index'
    else
      # flash [:notice] : 'something went wrong , please retry.'
      render 'new'
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to action: 'index', notice: 'post was successfully updated.'
    else
      #  flash[:notice] : 'something went wrong , please retry.'
      render 'edit'
    end
  end

  def show
    @blog_comments = @blog.comments
  end

  private

  def set_blog
    @blog = Blog.find_by_id(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: %i[edit update destroy show create]
  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to action: 'index' }
        format.js
      else
        format.html { redirect_to action: 'new' }
        format.js
      end
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to posts_url
    else
      redirect_to action: 'edit'
    end
  end

  def show; end

  def comment_new_first
    response = {}
    @comments = Comment.new
    @post = Post.find_by_id(params[:id])
    response[:comment] = @post.comments.create(title: params[:title])
    render json: response
  end

  def comment_new
    response = {}
    @comments = Comment.new
    @blog = Blog.find_by_id(params[:id])
    response[:comment] = @blog.comments.create(title: params[:title])
    render json: response
  end

  def destroy
    @comment.destroy
    # redirect_to action: "index"
  end

  def index
    @comments = Comment.all
  end

  private

  def find_comment
    @comment = Comment.find_by_id(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:title, :commentable_id, :commentable_type)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy show]

  def index
    @post = Post.all
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to action: 'index', notice: 'post was successfully destroyed.' }
      format.js { render layout: false }
    end
  end

  def edit; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      # flash[:notice] = 'post was successfully created.'
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to action: 'index', notice: 'post was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    @post_comments = @post.comments
  end

  private

  def set_post
    @post = Post.find_by_id(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, remote: true) do |form| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
  
        <ul>
          <% @blog.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

app/views/blogs/destroy.js.erb
$('.delete_blog').on('ajax:success', function(){
    $(this).closest('tr').fadeOut();
});

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table class= "table table-borderless">
<%if @blogs.present?%>
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
     
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_post_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } , :remote => true, :class => 'delete_blog'%></td>
      </tr>
    <% end %>
    <%else%>
    <tr class = "btn-danger" scope="row"> yet no blog</tr>
    <%end%>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @blog.description %>
</p>
<h1> Comments on this post</h1>
 <%if @blog_comments.present?%>
<table id = 'data' class= "table">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @blog.comments.each do |comment| %>
      <tr>
      <input type= 'hidden' name= 'id' value= '<%= comment.commentable_id %>' id= 'comment_id'>
        <td><%= comment.title %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } , :remote => true, :class => 'delete_comment'%></td>
      </tr>
    <% end %>
  </tbody>
  <%else%>
  <p> yet no comment</p>
  <%end%>
</table>

<%= link_to 'Edit this post', edit_post_path(@blog) %> |
<%= link_to 'Back to all post', blogs_path %>

<%#= link_to 'create new comment', '' , id: 'new_comment' %>
<button type="button" class="btn btn-primary"  data-toggle="modal" data-target="#exampleModal">
  Add new comment
</button>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    <%= form_with(model: @comment, :html=>{:id=>"myForm",:multipart => true,:remote=>true}) do |form| %>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title , :maxlength => 15 %>
      <%= form.hidden_field :id , value: params[:id]%>
    </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id = "close">Cancel</button>
        <button type="button" class="btn btn-primary" id ="new_comment">Submit</button>
        <%end%>
      </div>
    </div>
  </div>
</div>
<script>

$(function(){
  
  $(document).on('click', '#new_comment', function(e){
    e.preventDefault();
    var id = $('#id').val();
    $.ajax({
      type: "get",
      contentType: "application/json",      
      url: "/post/" + id + "/comment_new",
      data: { 
        title: $('#title').val(),
      },
      success: function(data){
       alert('comment has been succesfully added');
       $('#close').click();
       $("#data").load(location.href + " #data");
       $('#title').val('');
      }
    });
  })
})

</script>

app/views/comments/_form.html.erb
<%= form_with(model: @comment) do |form| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this pony from being saved:</h2>
  
        <ul>
          <% @comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/comments/comment_new.html.erb
  <%= render 'form', comment: @comment %>
  

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/destroy.js.erb
$('.delete_comment').on('ajax:success', function(){
    $(this).closest('tr').fadeOut();
});

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/new.html.erb
<h1>New Post</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
alert('hello');

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/home/index.html.erb
<% if user_signed_in? %>

<h1> user signed in as <strong class= "badge-success"><%= current_user.email%></strong></h1> <p class="center"><h1><%= link_to 'Post' ,posts_path %> | <%= link_to 'Blog' , blogs_path%></h1> <%= link_to 'log_out' , destroy_user_session_path , :method => :delete%></p>
<%else%>
<%= link_to 'log_in' , new_user_session %>| <%= link_ to 'sign_up' ,new_user_registration_path %>
<%end%>

app/views/layouts/application.html.erb
<%# app/views/layouts/application.html.erb %>
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBootstrap4Integration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this pony from being saved:</h2>
  
        <ul>
          <% @post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/posts/destroy.js.erb
$('.delete_comment').on('ajax:success', function(){
    $(this).closest('tr').fadeOut();
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post.each do |pony| %>
      <tr>
        <td><%= pony.title %></td>
        <td><%= pony.description %></td>
        <td><%= link_to 'Show', pony %></td>
        <td><%= link_to 'Edit', edit_post_path(pony) %></td>
        <td><%= link_to 'Destroy', pony, method: :delete, data: { confirm: 'Are you sure?' } , :remote => true, :class => 'delete_comment'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<style>
td {
                width:50px;
                padding:5px
              
            }
</style>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @post.description %>
</p>
<h1> Comments on this post</h1>
 <%if @post_comments.present?%>
<table id = 'data' class= "table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th colspan="1" scope="col">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @post_comments.each do |comment| %>
      <tr>
      <input type= 'hidden' name= 'id' value= '<%= comment.commentable_id %>' id= 'comment_id'>
        <td scope="row"><%= comment.title %></td>
        
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } , :remote => true, :class => 'delete_comment'%></td>
      </tr>
    <% end %>
  </tbody>
  <%else%>
  <p> yet no comment</p>
  <%end%>
</table>

<%= link_to 'Edit this post', edit_post_path(@post) %> |
<%= link_to 'Back to all post', posts_path %>

<%#= link_to 'create new comment', '' , id: 'new_comment' %>
<button type="button" class="btn btn-primary"  data-toggle="modal" data-target="#exampleModal">
  Add new comment
</button>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    <%= form_with(model: @comment, :html=>{:id=>"myForm",:multipart => true,:remote=>true}) do |form| %>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title , :maxlength => 15 %>
      <%= form.hidden_field :id , value: params[:id]%>
    </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id = "close">Cancel</button>
        <button type="button" class="btn btn-primary" id ="new_comment">Submit</button>
        <%end%>
      </div>
    </div>
  </div>
</div>
<script>

$(function(){
  
  $(document).on('click', '#new_comment', function(e){
    e.preventDefault();
    var id = $('#id').val();
    $.ajax({
      type: "get",
      contentType: "application/json",      
      url: "/post/" + id + "/comment_new_first",
      data: { 
        title: $('#title').val(),
      },
      success: function(data){
       alert('comment has been succesfully added');
       $('#close').click();
       $("#data").load(location.href + " #data");

       $('#title').val('');
      }
    });
  })
})

</script>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>